# Logging
logging:
  level:
    ROOT: info
    at.jku.dke: trace

# Data
spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/etutor_sql_ddl
    username: etutor_sql_ddl
    password: secret
  jpa:
    show-sql: true

# Springdoc
springdoc:
  show-actuator: true

# API key definition
clients:
  api-keys:
    - name: task-administration
      key: task-admin-key
      roles:
        - CRUD
        - SUBMIT
    - name: jobe-server
      key: jobe-server-key
      roles:
        - SUBMIT
    - name: plag-check
      key: plag-check-key
      roles:
        - READ_SUBMISSION

# JDBC
jdbc:
  url: jdbc:postgresql://localhost:5434/etutor_sql_ddl
  admin:
    username: etutor_sql_ddl
    password: secret
  max-pool-size: 10
  max-lifetime: 1800000 # 30 minutes
  connection-timeout: 15000 # 15 seconds
  driverClassName: org.postgresql.Driver
